# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: S3Upload@1
  inputs:
    awsCredentials: 'aws_service_connection'
    regionName: 'eu-west-1'
    bucketName: 'nvg-devopstest'
    sourceFolder: 'stack_template/'
    globExpressions: '**'
    targetFolder: 'stack_template/uploads_from_azure'