# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: S3Upload@1
  inputs:
    awsCredentials: 'aws_service_connection'
    regionName: 'eu-west-1'
    bucketName: 'nvg-devopstest'
    sourceFolder: '$(Build.SourcesDirectory)'
    globExpressions: '**'
    targetFolder: 'stack_template/uploads_from_azure'
    filesAcl: 'public-read-write'

- task: CloudFormationCreateOrUpdateStack@1
  inputs:
    awsCredentials: 'aws_service_connection'
    regionName: 'eu-west-1'
    stackName: 'Test-cf-stack'
    templateSource: 's3'
    s3BucketName: 'nvg-devopstest'
    s3ObjectKey: 'stack_template/akamai_sg.json'
